### ISSUE TITLE
Error connecting to database

### ISSUE THREAD

**Issue by Episki2001** [neallithic64/capstn-mmchd#16]
When attempting to do any action the following error appears:
```
Error: connect ETIMEDOUT
    at PromisePool.execute (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\mysql2\promise.js:359:22)
    at Object.findRows (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\models\db.js:103:36)
    at postLogin (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\controllers\m1Controller.js:57:25)
    at Layer.handle [as handle_request] (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\express\lib\router\layer.js:95:5)
    at D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\express\lib\router\index.js:275:10) {  code: 'ETIMEDOUT',
  errno: undefined,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}
```

**Comment by neallithic64** [comment]
forgot to update, but error has been resolved. the issue mainly comes from using a weird proxy problem on the side of the client.
- reconnecting to a different internet spot solved the issue.
- i suspect that this may also be solved by flushing the DNS and release/renew-ing the IP address through `ipconfig`
