### ISSUE TITLE
postRegisterUser function db connection has issue

### ISSUE THREAD

**Issue by Episki2001** [neallithic64/capstn-mmchd#8]
Upon attempting to call the function postRegisterUser to add the user to the database by using the link
http://localhost:8080/newUser, 
this error appears

Error: connect ECONNREFUSED 127.0.0.1:3306
    at PromisePool.query (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\node_modules\mysql2\promise.js:341:22)
    at Object.insertOne (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\models\db.js:86:36)
    at postRegUser (D:\Academics\Capstone\WebApplication\capstn-mmchd\server\controllers\m1Controller.js:80:26) {
  code: 'ECONNREFUSED',
  errno: -4078,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined

**Comment by neallithic64** [comment]
issue was caused by wrong environment variables, with incomplete credentials. solved by having the correct .env file. closing this.
